name: release_build

on:
  release:
    types: [created]

jobs:
  bauen:
    runs-on: ubuntu-latest

    steps:
      - name: Code holen
        uses: actions/checkout@v3

      - name: Node.js installieren
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Pakete installieren
        run: npm ci

      - name: App bauen
        run: npm run build

      - name: ZIP erstellen
        run: |
          cd dist
          zip -r ../futur-o-mat.zip .

      - name: ZIP hochladen
        uses: softprops/action-gh-release@v1
        with:
          files: futur-o-mat.zip
